# Generated by Django 3.2.7 on 2021-09-09 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='gender',
            field=models.CharField(default=2, max_length=50, verbose_name='Sexo'),
            preserve_default=False,
        ),
    ]
